### ISSUE TITLE
move note to different notebook

### ISSUE THREAD

**Issue by fnkr** [evernote/evernote-cloud-sdk-php#4]
How to move a note to a different notebook?

**Comment by gockxml** [comment]
Hi, I find that when moving a note between two business notebook on Evernote client or Evernote Web, the note's guid stays the same. However using your `moveNote` needs to create a whole new note. Can you explain it?

**Comment by Laurent-Sarrazin** [comment]
Hi, 
when you move a note, it actually creates a copy then deletes the original. That's why you get a different guid. 
It's the behaviour of the desktop client too. The only difference is that the desktop client completely deletes the original note (and doesn't puts it in the trash) whereas the api puts the file in the trash as it cannot use the expungeNote() method.

**Comment by gockxml** [comment]
@Laurent-Sarrazin I understand the copy-and-delete method. However, what I'm trying to say is that your official desktop and web clients seem not using this method because the guid doesn't change after moving between business account.

Only when I move a note from a business notebook to a personal notebook, it seems using your copy-and-delete way because it shows me a message like "Moving note requires some time blabla".

You can have a try in your Evernote clients. My question is how to move a note between business account without changing the guid? Is there any internal API?
