### ISSUE TITLE
Issue creating attachment

### ISSUE THREAD

**Issue by kevinwithnall** [evernote/evernote-cloud-sdk-php#6]
I can use the sample code to create notes with text such as

$note         = new \Evernote\Model\Note();
$note->title  = 'Test note';
$note->content = new \Evernote\Model\PlainTextNoteContent('Some plain text content.');

But when  I do something like
$resource = new \Evernote\Model\Resource("/root/BTSync/enupload/TestFiles/test.txt.pdf");
$note->addResource($resource);

It doesn't throw any errors (and if i print_r($resource) I get all the data) but the note is then created without the attachment.

There are no samples of adding a resource to a note that I can see so I may be doing it incorrectly.

Thanks for your time.

**Comment by Laurent-Sarrazin** [comment]
Hi Kevin, 

actually there's a [sample](https://github.com/evernote/evernote-cloud-sdk-php/blob/master/sample/client/add_resource.php)

It seems that you forgot to add the pdf in the ENML : 
In this case you can't use the PlainText mode as you need to add the en-media tag : 

```php
$resource = new \Evernote\Model\Resource("/root/BTSync/enupload/TestFiles/test.txt.pdf");
$enml_media_tag = $resource->getEnmlMediaTag();
// Create the note
$note = new \Evernote\Model\Note();
$note->addResource($resource);
$note->title  = 'Test note';
$note->content = new \Evernote\Model\EnmlNoteContent(
    <<<ENML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">
<en-note>$enml_media_tag</en-note>
ENML
);
```

Otherwise the pdf is uploaded but not displayed in the note
